--- #YAML:1.0
name:               Linux-Btldr-Pxelinux
version:            0.23
abstract:           generate configuration files for pxelinux
author:
    - David Muir Sharnoff <cpan@dave.sharnoff.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    File::Temp:    0
    FindBin:       0
    Test::More:    0
    Test::Output:  0
requires:
    File::Slurp:   0
    Getopt::Long:  0
resources:
    repository:  http://github.com/muir/genpxelinux.pl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
